### ISSUE TITLE
More robust airfoil extrapolations/corrections

### ISSUE THREAD

**Issue by juddmehr** [byuflowlab/FLOWVLM#17]
Occasionally, the airfoil data extrapolations and corrections produce odd results.  Looking into some more robust options/algorithms for that.

**Comment by andrewning** [comment]
whatever we do we should do this in one place, rather than repeating in multiple repos.  That may mean that I change CCBlade to use AirfoilPrep.jl - and we make airfoil prep pure julia - I already have that in CCBlade though may not provide all the same functionality and some of the methods certainly could be improved.

**Comment by juddmehr** [comment]
Not sure the best way to do this.  Right now I just copied and pasted the CCBlade functions.  I don't think that FLOWUnsteady uses the most up to date CCBlade.

I've also adjusted things in FLOWVLM to allow for user-corrected data to get input directly rather than requiring FLOWVLM to do its own corrections.
